name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install and Build
      run: |
        cd stock/volume-price-analyzer
        npm install
        npm run build
        
    - name: Create deployment structure
      run: |
        mkdir -p dist
        cp index.html dist/
        if [ -d "common" ]; then cp -r common dist/; fi
        mkdir -p dist/stock/volume-price-analyzer
        cp -r stock/volume-price-analyzer/build/* dist/stock/volume-price-analyzer/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
