name: Deploy Volume Price Analyzer

on:
  push:
    branches: [ master, main ]
    paths: 
      - 'stock/volume-price-analyzer/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: stock/volume-price-analyzer/package-lock.json
        
    - name: Install dependencies
      run: |
        cd stock/volume-price-analyzer
        npm ci
        
    - name: Build project
      run: |
        cd stock/volume-price-analyzer
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: stock/volume-price-analyzer/build
        destination_dir: stock/volume-price-analyzer
        keep_files: true
        exclude_assets: '.github'
